<a href="https://colab.research.google.com/github/RitwikRocks/01ReactBackGroundChanger/blob/main/CROP_PREDICION_SYSTEM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Crop Recommendation SYSTEM

## We will be using Classifaction Technique to predict the crop.


### Importing Libraries required for processing

In [84]:
import pandas as pd
import numpy as np

### Importing the Data Set

In [85]:
dataset = pd.read_csv("data.csv")
print(dataset['label'].unique())
X = dataset.iloc[:,:-1]
Y = dataset.iloc[:,-1].values

['rice' 'maize' 'chickpea' 'kidneybeans' 'pigeonpeas' 'mothbeans'
 'mungbean' 'blackgram' 'lentil' 'watermelon' 'muskmelon' 'cotton' 'jute']


In [86]:
print(X)
X['season'].unique()


      temperature   humidity        ph  water availability season
0       20.879744  82.002744  6.502985          202.935536  rainy
1       21.770462  80.319644  7.038096          226.655537  rainy
2       23.004459  82.320763  7.840207          263.964248  rainy
3       26.491096  80.158363  6.980401          242.864034  rainy
4       20.130175  81.604873  7.628473          262.717340  rainy
...           ...        ...       ...                 ...    ...
1395    23.874845  86.792613  6.718725          177.514731  rainy
1396    23.928879  88.071123  6.880205          154.660874  rainy
1397    24.814412  81.686889  6.861069          190.788639  rainy
1398    24.447439  82.286484  6.769346          190.968489  rainy
1399    26.574217  73.819949  7.261581          159.322307  rainy

[1400 rows x 5 columns]


array(['rainy', 'winter', 'spring', 'summer'], dtype=object)

### Encoding the categorical Data
We have to converting categorical data into numerical format.machine learning algorithms require numerical input to make predictions, these encoding methods simplify categorical variables, enabling algorithms to identify patterns and relationships in the data.

In [87]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X['season'] = le1.fit_transform(X['season'])
print(X['season'].unique())

[0 3 1 2]


In [88]:
X = X.iloc[:, :].values
print(X)

[[ 20.87974371  82.00274423   6.50298529 202.9355362    0.        ]
 [ 21.77046169  80.31964408   7.03809636 226.6555374    0.        ]
 [ 23.00445915  82.3207629    7.84020714 263.9642476    0.        ]
 ...
 [ 24.81441246  81.68688879   6.86106911 190.7886386    0.        ]
 [ 24.44743944  82.286484     6.7693455  190.9684885    0.        ]
 [ 26.57421679  73.81994896   7.26158085 159.3223075    0.        ]]


In [89]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')  #Encoding the independent variable or feature matrix
# X = np.array(ct.fit_transform(X))

In [90]:

le = LabelEncoder()
Y=le.fit_transform(Y)


In [91]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)


### Feature Scaling the model
Feature Scaling is applied only on the non encoded values

In [92]:
value_temp=X_train[399]
print(value_temp.reshape(-1,1))

[[ 22.70883798]
 [ 82.63941394]
 [  5.70080568]
 [271.3248604 ]
 [  0.        ]]


In [93]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,:4] = sc.fit_transform(X_train[:,:4])
X_test[:,:4] = sc.transform(X_test[:,:4])

In [94]:
value_temp=X_train[399]
print(value_temp.reshape(-1,1))

[[-0.57493061]
 [ 0.77997706]
 [-1.08218208]
 [ 3.13424592]
 [ 0.        ]]


### Applying the RandomForest Classification

In [95]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators=100,criterion='entropy')
classifier_rf.fit(X_train,Y_train)

RandomForestClassifier(criterion='entropy')

In [96]:
Y_pred_random_forest = classifier_rf.predict(X_test)
print(np.concatenate((Y_test.reshape(len(Y_test),1),Y_pred_random_forest.reshape(len(Y_pred_random_forest),1)),1))


[[ 9  9]
 [ 4  4]
 [ 0  0]
 [10 10]
 [12 12]
 [ 3  3]
 [ 3  3]
 [10 10]
 [ 6  6]
 [ 7  7]
 [ 1  1]
 [12 12]
 [ 6  6]
 [ 8  8]
 [ 6  6]
 [ 1  1]
 [ 5  5]
 [ 4  4]
 [ 9  9]
 [ 2  2]
 [ 9  9]
 [ 5  5]
 [ 5  5]
 [ 1  1]
 [ 1  1]
 [ 0  0]
 [ 4  4]
 [10 10]
 [ 0  0]
 [ 0  0]
 [11 11]
 [ 6  6]
 [ 6  6]
 [10 10]
 [ 8  8]
 [ 6  6]
 [ 4  4]
 [ 9  9]
 [ 1  1]
 [11 11]
 [ 7  7]
 [ 7  7]
 [ 9  9]
 [ 2  2]
 [ 0  0]
 [ 6  6]
 [ 7  7]
 [ 6  0]
 [12 12]
 [ 2  2]
 [ 1  1]
 [ 2  2]
 [ 7  7]
 [ 4  4]
 [ 9  9]
 [10 10]
 [12 12]
 [ 4  4]
 [ 1  1]
 [10 10]
 [ 6  6]
 [10 10]
 [ 4  4]
 [11 11]
 [ 6  6]
 [ 0  0]
 [10 10]
 [12 12]
 [10 10]
 [ 0  0]
 [ 6  6]
 [ 2  2]
 [ 9  9]
 [ 6  6]
 [ 9  9]
 [ 6  6]
 [ 9  9]
 [ 8  8]
 [ 6  6]
 [11 11]
 [ 0  0]
 [ 2  2]
 [11 11]
 [ 8  8]
 [11  3]
 [ 2  2]
 [11 11]
 [ 0  0]
 [ 8  8]
 [12 12]
 [ 3  3]
 [ 3  3]
 [ 2  2]
 [ 1  1]
 [ 3  3]
 [11  3]
 [ 4  4]
 [ 5  5]
 [12 12]
 [ 6  6]
 [ 2  2]
 [ 5  5]
 [ 5  5]
 [ 0  0]
 [ 2  2]
 [ 5  5]
 [ 1  1]
 [12 12]
 [ 2  2]
 [ 8  8]
 [ 6  6]
 

In [97]:

from sklearn.metrics import confusion_matrix, accuracy_score

confusion_matrix_random_forest = confusion_matrix(Y_test,Y_pred_random_forest)
score_random_forest = accuracy_score(Y_test,Y_pred_random_forest)

print(f"The Confusion matix of the Dataset using the Random Forest Model is:\n")
print(confusion_matrix_random_forest)
print(f"The accuracy score of the Dataset using Random Forest Model is : {score_random_forest}")

The Confusion matix of the Dataset using the Random Forest Model is:

[[18  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 26  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 17  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0 20  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0 40  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 25  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 13  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 17  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 24  0  0]
 [ 0  0  0  2  0  0  0  0  0  0  0 26  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 15]]
The accuracy score of the Dataset using Random Forest Model is : 0.9857142857142858


## K Nearest Neighbour
In this classification model
Step 1- choose the number K of how many neighbours we consider.
Step 2 - choose the K nearest neighbour according to the Eucledian Distance between the observing point and the other points\
Step 3 - predict the result from it

In [98]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors=3,weights='uniform',algorithm='auto',p=3,metric='minkowski')
classifier_knn.fit(X_train,Y_train)

KNeighborsClassifier(n_neighbors=3, p=3)

In [99]:
Y_pred_knn = classifier_knn.predict(X_test)
print(np.concatenate((Y_test.reshape(len(Y_test),1),Y_pred_knn.reshape(len(Y_pred_knn),1)),1))

[[ 9  9]
 [ 4  4]
 [ 0  0]
 [10 10]
 [12 12]
 [ 3  3]
 [ 3  3]
 [10 10]
 [ 6  6]
 [ 7  7]
 [ 1  1]
 [12 12]
 [ 6  6]
 [ 8  8]
 [ 6  6]
 [ 1  1]
 [ 5  5]
 [ 4  4]
 [ 9  9]
 [ 2  2]
 [ 9  9]
 [ 5  5]
 [ 5  5]
 [ 1  1]
 [ 1  1]
 [ 0  0]
 [ 4  4]
 [10 10]
 [ 0  0]
 [ 0  0]
 [11 11]
 [ 6  6]
 [ 6  6]
 [10 10]
 [ 8  8]
 [ 6  6]
 [ 4  4]
 [ 9  9]
 [ 1  1]
 [11 11]
 [ 7  7]
 [ 7  7]
 [ 9  9]
 [ 2  2]
 [ 0  0]
 [ 6  6]
 [ 7  7]
 [ 6  6]
 [12 12]
 [ 2  2]
 [ 1  1]
 [ 2  2]
 [ 7  7]
 [ 4  4]
 [ 9  9]
 [10 10]
 [12 12]
 [ 4  4]
 [ 1  1]
 [10 10]
 [ 6  6]
 [10 10]
 [ 4  4]
 [11 11]
 [ 6  6]
 [ 0  0]
 [10 10]
 [12 12]
 [10 10]
 [ 0  0]
 [ 6  6]
 [ 2  2]
 [ 9  9]
 [ 6  6]
 [ 9  9]
 [ 6  6]
 [ 9  9]
 [ 8  8]
 [ 6  6]
 [11 11]
 [ 0  0]
 [ 2  2]
 [11 11]
 [ 8  8]
 [11  3]
 [ 2  2]
 [11 11]
 [ 0  0]
 [ 8  8]
 [12 12]
 [ 3  3]
 [ 3  3]
 [ 2  2]
 [ 1  1]
 [ 3  3]
 [11  3]
 [ 4  4]
 [ 5  5]
 [12 12]
 [ 6  2]
 [ 2  2]
 [ 5  5]
 [ 5  5]
 [ 0  0]
 [ 2  2]
 [ 5  5]
 [ 1  1]
 [12 12]
 [ 2  2]
 [ 8  8]
 [ 6  6]
 

In [100]:
confusion_matrix_knn = confusion_matrix(Y_test,Y_pred_knn)
score_knn = accuracy_score(Y_test,Y_pred_knn)

print(f"The Confusion matix of the Dataset using the K Nearest Neighbour is:\n")
print(confusion_matrix_knn)
print(f"The accuracy score of the Dataset using K Nearest Neighbour Model is : {score_knn}")

The Confusion matix of the Dataset using the K Nearest Neighbour is:

[[18  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 26  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 18  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 20  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0 40  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 25  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 13  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 17  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 24  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0 25  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 15]]
The accuracy score of the Dataset using K Nearest Neighbour Model is : 0.9857142857142858


# Support Vector Machines

This is an ML algorithm which works by compairing the most extreme parameters which helps in discriminating two different things. SVMs find a hyperplane (a line in 2D or a plane in higher dimensions) that best separates data points belonging to different classes, maximizing the margin (distance) between the hyperplane and the nearest data points from each class. These nearest points are called support vectors.
For Example - If we want to differentiate between apples and oranges, most of the ordinary ml algo will look for the parameters of most applish apple and orangish orange and learn from them. But if we see about the SVMs then it will look for most orangish apple and applish oranges and make the support vectors and hyperplane based on this it becomes very powerful.

## Linear SVM Implemenation

In [101]:
from sklearn.svm import SVC
classifier_svm_linear = SVC(kernel='linear', random_state=0)
classifier_svm_linear.fit(X_train,Y_train)

SVC(kernel='linear', random_state=0)

In [102]:
Y_pred_svm_linear = classifier_svm_linear.predict(X_test)
#print(Y_pred_svm_linear)
print(np.concatenate((Y_test.reshape(len(Y_test),1),Y_pred_svm_linear.reshape(len(Y_pred_svm_linear),1)),1))

[[ 9  9]
 [ 4  4]
 [ 0  0]
 [10 10]
 [12 12]
 [ 3  3]
 [ 3  3]
 [10  3]
 [ 6  6]
 [ 7  7]
 [ 1  1]
 [12 12]
 [ 6  6]
 [ 8  8]
 [ 6  6]
 [ 1  1]
 [ 5  5]
 [ 4  4]
 [ 9  9]
 [ 2  2]
 [ 9  9]
 [ 5  6]
 [ 5  5]
 [ 1  1]
 [ 1  1]
 [ 0  0]
 [ 4  4]
 [10 10]
 [ 0  0]
 [ 0  0]
 [11 11]
 [ 6  6]
 [ 6  6]
 [10 10]
 [ 8  8]
 [ 6  6]
 [ 4  4]
 [ 9  9]
 [ 1  1]
 [11 11]
 [ 7  7]
 [ 7  7]
 [ 9  9]
 [ 2  2]
 [ 0  0]
 [ 6  6]
 [ 7  7]
 [ 6  6]
 [12 12]
 [ 2  2]
 [ 1  1]
 [ 2  2]
 [ 7  7]
 [ 4  4]
 [ 9  9]
 [10 10]
 [12 12]
 [ 4  4]
 [ 1  1]
 [10 10]
 [ 6  6]
 [10 10]
 [ 4  4]
 [11 11]
 [ 6  6]
 [ 0  0]
 [10 10]
 [12 12]
 [10 10]
 [ 0  0]
 [ 6  6]
 [ 2  2]
 [ 9  9]
 [ 6  6]
 [ 9  9]
 [ 6  6]
 [ 9  9]
 [ 8  8]
 [ 6  6]
 [11 11]
 [ 0  0]
 [ 2  2]
 [11 11]
 [ 8  8]
 [11  3]
 [ 2  2]
 [11 11]
 [ 0  0]
 [ 8  8]
 [12 12]
 [ 3  3]
 [ 3  3]
 [ 2  2]
 [ 1  1]
 [ 3  3]
 [11  3]
 [ 4  4]
 [ 5  5]
 [12 12]
 [ 6  2]
 [ 2  2]
 [ 5  5]
 [ 5  5]
 [ 0  0]
 [ 2  2]
 [ 5  5]
 [ 1  1]
 [12 12]
 [ 2  2]
 [ 8  8]
 [ 6  6]
 

In [103]:
confusion_matrix_svm = confusion_matrix(Y_test,Y_pred_svm_linear)
score_svm = accuracy_score(Y_test,Y_pred_svm_linear)

print(f"The Confusion matix of the Dataset using the SVM Model With Linear Kernal is:\n")
print(confusion_matrix_svm)
print(f"The accuracy score of the Dataset using SVM Model With Linear Kernal is : {score_svm}")

The Confusion matix of the Dataset using the SVM Model With Linear Kernal is:

[[18  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 26  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 17  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0 20  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 14  1  0  0  0  0  0  0]
 [ 0  0  1  0  0  0 40  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 25  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 13  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 17  0  0  0]
 [ 0  0  0  1  0  0  1  0  0  0 22  0  0]
 [ 0  0  0  5  0  0  0  0  0  0  0 23  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 15]]
The accuracy score of the Dataset using SVM Model With Linear Kernal is : 0.9642857142857143


## Limitations of SVM With Linear Kernal
In SVM with Linear Kernal , we have straight line which is used to differentate the two zones if we comapare about classification of 2 objects. But in reality most of the time the seperation demands the curved lines rather than seperate so we use a non linear kernal to seperate them. In this way our predicition can improve.

## SVM With Non Linear Kernal

In [104]:
from sklearn.svm import SVC
classifier_svm_kernel = SVC(kernel='rbf', gamma='auto',decision_function_shape='ovr')
classifier_svm_kernel.fit(X_train,Y_train)

SVC(gamma='auto')

In [105]:
Y_pred_svm_kernel = classifier_svm_kernel.predict(X_test)
print(np.concatenate((Y_test.reshape(len(Y_test),1),Y_pred_svm_kernel.reshape(len(Y_pred_svm_kernel),1)),1))

[[ 9  9]
 [ 4  4]
 [ 0  0]
 [10 10]
 [12 12]
 [ 3  3]
 [ 3  3]
 [10 10]
 [ 6  6]
 [ 7  7]
 [ 1  1]
 [12 12]
 [ 6  6]
 [ 8  8]
 [ 6  6]
 [ 1  1]
 [ 5  5]
 [ 4  4]
 [ 9  9]
 [ 2  2]
 [ 9  9]
 [ 5  6]
 [ 5  5]
 [ 1  1]
 [ 1  1]
 [ 0  0]
 [ 4  4]
 [10 10]
 [ 0  0]
 [ 0  0]
 [11 11]
 [ 6  6]
 [ 6  6]
 [10 10]
 [ 8  8]
 [ 6  6]
 [ 4  4]
 [ 9  9]
 [ 1  1]
 [11 11]
 [ 7  7]
 [ 7  7]
 [ 9  9]
 [ 2  2]
 [ 0  0]
 [ 6  6]
 [ 7  7]
 [ 6  6]
 [12 12]
 [ 2  2]
 [ 1  1]
 [ 2  2]
 [ 7  7]
 [ 4  4]
 [ 9  9]
 [10 10]
 [12 12]
 [ 4  4]
 [ 1  1]
 [10 10]
 [ 6  6]
 [10 10]
 [ 4  4]
 [11 11]
 [ 6  6]
 [ 0  0]
 [10 10]
 [12 12]
 [10 10]
 [ 0  0]
 [ 6  6]
 [ 2  2]
 [ 9  9]
 [ 6  6]
 [ 9  9]
 [ 6  6]
 [ 9  9]
 [ 8  8]
 [ 6  6]
 [11 11]
 [ 0  0]
 [ 2  2]
 [11 11]
 [ 8  8]
 [11  3]
 [ 2  2]
 [11 11]
 [ 0  0]
 [ 8  8]
 [12 12]
 [ 3  3]
 [ 3  3]
 [ 2  2]
 [ 1  1]
 [ 3  3]
 [11  3]
 [ 4  4]
 [ 5  5]
 [12 12]
 [ 6  2]
 [ 2  2]
 [ 5  5]
 [ 5  5]
 [ 0  0]
 [ 2  2]
 [ 5  5]
 [ 1  1]
 [12 12]
 [ 2  2]
 [ 8  8]
 [ 6  6]
 

In [106]:
confusion_matrix_svm = confusion_matrix(Y_test,Y_pred_svm_kernel)
score_svm = accuracy_score(Y_test,Y_pred_svm_kernel)

print(f"The Confusion matix of the Dataset using the SVM Model With Gaussian Kernal is:\n")
print(confusion_matrix_svm)
print(f"The accuracy score of the Dataset using SVM Model With Non Linear Kernal is : {score_svm}")

The Confusion matix of the Dataset using the SVM Model With Gaussian Kernal is:

[[18  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 26  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 17  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0 20  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 13  2  0  0  0  0  0  0]
 [ 0  0  1  0  0  0 40  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 25  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 13  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 17  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 24  0  0]
 [ 0  0  0  4  0  0  0  0  0  0  0 24  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 15]]
The accuracy score of the Dataset using SVM Model With Non Linear Kernal is : 0.9714285714285714


#Naive Bayer Classification
It is based on the bayes theorem of probability. We use prior probabiliy , marginal likelihood and likelihood. Based on this we find Posterior Probability. It is called naive as it is based on the independent assumptions which are mostly naive.

In [107]:
from sklearn.naive_bayes import GaussianNB
classifier_naive_bayes = GaussianNB()
classifier_naive_bayes.fit(X_train,Y_train)

GaussianNB()

In [108]:
Y_pred_naive_bayes = classifier_naive_bayes.predict(X_test)
print(np.concatenate((Y_test.reshape(len(Y_test),1),Y_pred_naive_bayes.reshape(len(Y_pred_naive_bayes),1)),1))

[[ 9  9]
 [ 4  4]
 [ 0  0]
 [10 10]
 [12 12]
 [ 3  3]
 [ 3  3]
 [10 10]
 [ 6  0]
 [ 7  7]
 [ 1  1]
 [12 12]
 [ 6 10]
 [ 8  8]
 [ 6  0]
 [ 1  1]
 [ 5  5]
 [ 4  4]
 [ 9  9]
 [ 2  2]
 [ 9  9]
 [ 5  5]
 [ 5  5]
 [ 1  1]
 [ 1  1]
 [ 0  0]
 [ 4  4]
 [10 10]
 [ 0  0]
 [ 0  0]
 [11 11]
 [ 6 10]
 [ 6  6]
 [10 10]
 [ 8  8]
 [ 6  0]
 [ 4  4]
 [ 9  9]
 [ 1  1]
 [11 11]
 [ 7  7]
 [ 7  7]
 [ 9  9]
 [ 2  2]
 [ 0  0]
 [ 6  2]
 [ 7  7]
 [ 6  2]
 [12 12]
 [ 2  2]
 [ 1  1]
 [ 2  2]
 [ 7  7]
 [ 4  4]
 [ 9  9]
 [10 10]
 [12 12]
 [ 4  4]
 [ 1  1]
 [10 10]
 [ 6  6]
 [10 10]
 [ 4  4]
 [11 11]
 [ 6 10]
 [ 0  0]
 [10 10]
 [12 12]
 [10 10]
 [ 0  0]
 [ 6  5]
 [ 2  2]
 [ 9  9]
 [ 6  6]
 [ 9  9]
 [ 6  2]
 [ 9  9]
 [ 8  8]
 [ 6 10]
 [11 11]
 [ 0  0]
 [ 2  2]
 [11 11]
 [ 8  8]
 [11  3]
 [ 2  2]
 [11 11]
 [ 0  0]
 [ 8  8]
 [12 12]
 [ 3  3]
 [ 3  3]
 [ 2  2]
 [ 1  1]
 [ 3 11]
 [11 11]
 [ 4  4]
 [ 5  5]
 [12 12]
 [ 6  2]
 [ 2  2]
 [ 5  5]
 [ 5  5]
 [ 0  0]
 [ 2  2]
 [ 5  5]
 [ 1  1]
 [12 12]
 [ 2  2]
 [ 8  8]
 [ 6 10]
 

In [109]:
confusion_matrix_naive_bayes = confusion_matrix(Y_test,Y_pred_naive_bayes)
score_naive_bayes = accuracy_score(Y_test,Y_pred_naive_bayes)

print(f"The Confusion matix of the Dataset using the Naive Bayes is:\n")
print(confusion_matrix_naive_bayes)
print(f"The accuracy score of the Dataset using Naive Bayes is : {score_naive_bayes}")

The Confusion matix of the Dataset using the Naive Bayes is:

[[18  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 26  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 16  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0 20  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0  0  0  0]
 [ 9  0  6  0  0  1 11  0  0  0 14  0  0]
 [ 0  0  0  0  0  0  0 25  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 13  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 17  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 24  0  0]
 [ 0  0  0  2  0  0  0  0  0  0  0 26  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 15]]
The accuracy score of the Dataset using Naive Bayes is : 0.8785714285714286


## We will give the user input and the model will give the result


In [110]:
valid_seasons = ['rainy', 'winter', 'spring', 'summer']
temperature = float(input("Enter the temperature: "))
humidity = float(input("Enter the humidity: "))
ph = float(input("Enter the pH level: "))
water_availability = float(input("Enter water availability Amount: "))
season = input("Enter the season (rainy, winter, spring, summer): ").strip().lower()

while season not in valid_seasons:
    print("Invalid season. Please enter one of the following: rainy, winter, spring, summer.")
    season = input("Enter the season (rainy, winter, spring, summer): ").strip().lower()


[season] = le1.transform([season])

X_pred = [temperature,humidity,ph,water_availability,season]
[X_pred[:4]] = sc.transform([X_pred[:4]])
Y_pred = classifier_knn.predict([X_pred])
print(f"\n\nThe Most suitable crop for the given data will be : {le.inverse_transform(Y_pred)}")

KeyboardInterrupt: Interrupted by user